### ISSUE TITLE
Working through the lesson - corrections

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop2022-lesson-cmssw#1]
## 02

- [x] to the CMSSW_5_3_32/src -> to the CMSSW_7_6_7/src
- [x] when opening the container, this is default area (cd does not harm though...) maybe worth mentioning

## 04

- [x] tell them to edit with the usual editor on the local computer instead of `nano`. This would be consistent with the docker tutorial in which we say
  > Open the ConfFile_cfg.py in the Demo/DemoAnalyzer/python directory with your normal editor on your local computer.You will find the Demo area under the cms_open_data_work/CMSSW_7_6_7/src directory on your local computer. As the working directory has been mounted into the container, all changes take effect there as well.
  - if nano is someone's normal editor, they can still use it... During the pre-exercises we should encourage people to use the editors that they normally use and get them into the habit of editing code on the local computer and compiling and running in the container
- [x] for `scram b`, tell to go to the container prompt

## 05

- [x] again, remove the suggestion for `nano`
- [x] before python check and `scram b` remind of doing it in the container

**Comment by katilp** [comment]
@caredg Are you OK with these changes? I can do the updates if you like

**Comment by caredg** [comment]
@katilp yes, certainly.  I have to take care of a couple of things before I go back to updating the tutorial page for the workshop and the indico page.  If you can, please go ahead with these changes.  Otherwise I will come back to them in a couple of hours. Thanks
